config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :hunts
  resource :session, only: [:new, :create, :destroy]

  root 'hunts#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

end

app/models/hunt.rb
class Hunt < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, uniqueness: true,
            length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil if session[:user_id].nil?
    User.find(session[:user_id])
  end
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController
  before_action :set_hunt, only: [:show, :edit, :update, :destroy]

  # GET /hunts
  # GET /hunts.json
  def index
    @hunts = Hunt.all
  end

  # GET /hunts/1
  # GET /hunts/1.json
  def show
  end

  # GET /hunts/new
  def new
    @hunt = Hunt.new
  end

  # GET /hunts/1/edit
  def edit
  end

  # POST /hunts
  # POST /hunts.json
  def create
    @hunt = Hunt.new(hunt_params)

    respond_to do |format|
      if @hunt.save
        format.html { redirect_to @hunt, notice: 'Hunt was successfully created.' }
        format.json { render :show, status: :created, location: @hunt }
      else
        format.html { render :new }
        format.json { render json: @hunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hunts/1
  # PATCH/PUT /hunts/1.json
  def update
    respond_to do |format|
      if @hunt.update(hunt_params)
        format.html { redirect_to @hunt, notice: 'Hunt was successfully updated.' }
        format.json { render :show, status: :ok, location: @hunt }
      else
        format.html { render :edit }
        format.json { render json: @hunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hunts/1
  # DELETE /hunts/1.json
  def destroy
    @hunt.destroy
    respond_to do |format|
      format.html { redirect_to hunts_url, notice: 'Hunt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hunt
      @hunt = Hunt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hunt_params
      params.require(:hunt).permit(:name, :steal, :strategy, :level)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by username: params[:username]

    session[:user_id] = user.id if not user.nil?

    redirect_to user
  end

  def destroy
    session[:user_id] = nil

    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hunts_helper.rb
module HuntsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hunts/_form.html.erb
<%= form_for(@hunt) do |f| %>
  <% if @hunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hunt.errors.count, "error") %> prohibited this hunt from being saved:</h2>

      <ul>
      <% @hunt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :steal %><br>
    <%= f.text_field :steal %>
  </div>

  <div class="field">
    <%= f.label :strategy %><br>
    <%= f.text_field :strategy %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hunts/edit.html.erb
<h1>Editing Hunt</h1>

<%= render 'form' %>

<%= link_to 'Show', @hunt %> |
<%= link_to 'Back', hunts_path %>

app/views/hunts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hunts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Steal</th>
      <th>Strategy</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hunts.each do |hunt| %>
      <tr>
        <td><%= hunt.name %></td>
        <td><%= hunt.steal %></td>
        <td><%= hunt.strategy %></td>
        <td><%= hunt.level %></td>
        <td><%= link_to 'Show', hunt %></td>
        <td><%= link_to 'Edit', edit_hunt_path(hunt) %></td>
        <td><%= link_to 'Destroy', hunt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hunt', new_hunt_path %>

app/views/hunts/new.html.erb
<h1>New Hunt</h1>

<%= render 'form' %>

<%= link_to 'Back', hunts_path %>

app/views/hunts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hunt.name %>
</p>

<p>
  <strong>Steal:</strong>
  <%= @hunt.steal %>
</p>

<p>
  <strong>Strategy:</strong>
  <%= @hunt.strategy %>
</p>

<p>
  <strong>Level:</strong>
  <%= @hunt.level %>
</p>

<%= link_to 'Edit', edit_hunt_path(@hunt) %> |
<%= link_to 'Back', hunts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ffxiihunts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navibar">
    <%= link_to 'hunts', hunts_path %>
    <%= link_to 'users', users_path %>
    <% if current_user.nil? %>
        <%= link_to 'sign in', signin_path %>
    <% else %>
        <%= link_to 'sign out', signout_path %>
    <% end %>
  </div>


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>